import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Make sure your globals.css includes your tailwind directives
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import CustomNav from "@/components/custom-nav";
import CustomFooter from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <div className="contents"> {/* This wrapper helps contain Theme */}
          <Theme className=" contents"> {/* Using contents to prevent Theme from creating its own box */}
            <CustomNav />
            <div className="">{children}</div>
          </Theme>
        </div>
        <CustomFooter />
      </body>
    </html>
  );
}